spring.application.name=tutorial

#Database
#Esto es para que Spring sepa que la BD será en memoria, que use motor de H2, la cree automática desde el modelo y use el fichero data.sql.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.h2.console.enabled=true